### ISSUE TITLE
Add raptoreum CPU hashing algorithm

### ISSUE THREAD

**Issue by Warchant** [VeriBlock/vbk-ri-btc#661]
BTCSQ should use hashining algorithm which is calculated on CPUs. One example is raptoreum - 
https://github.com/HatcherMine/Raptoreum-Miner/tree/main/algo/gr 
https://github.com/Raptor3um/raptoreum/blob/master/src/primitives/block.cpp#L33-L46

Tasks:
- [ ] VeriBlock/vbk-ri-btc#662
- [ ] VeriBlock/nodecore-js#49
- [ ] https://github.com/VeriBlock/vbk-ri-stratum-pool/issues/5
- [ ] https://github.com/VeriBlock/vbk-ri-btc-explorer/issues/11
- [ ] VeriBlock/vbk-ri-btc-cpuminer#5
